TRAIN:
  OPTIMIZER:
    NAME: ADAMW
    EPS: 1e-4
  BASE_LR: 3e-5
  WARMUP_LR: 5e-7
  MIN_LR: 5e-6
  WEIGHT_DECAY: 5e-4
  EPOCHS: 300
DATA:
  IMG_SIZE: 256
  DATASET: gid
  BATCH_SIZE: 16
MODEL:
  TYPE: mynet
  NAME: swanet_v4
  NUM_CLASSES: 15
  DROP_PATH_RATE: 0.5
  SWINV2:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 8
  DECODER:
    DEPTH: [4, 3, 2, 1]
    GVI_NUMS: [8, 8, 12, 16]
    FEATURES: [8, 16, 24, 32]
SAVE_FREQ: 20