TRAIN:
  OPTIMIZER:
    NAME: ADAMW
    EPS: 1e-8
  LR_SCHEDULER:
    DECAY_RATE: 0.8
    DECAY_EPOCHS: 40
  BASE_LR: 6e-6
  WARMUP_LR: 5e-8
  MIN_LR: 5e-8
  WEIGHT_DECAY: 1e-2
  EPOCHS: 300
DATA:
  IMG_SIZE: 256
  DATASET: gid
  BATCH_SIZE: 16
MODEL:
  TYPE: mynet
  NAME: swanet_v4
  NUM_CLASSES: 15
  DROP_PATH_RATE: 0.3
  SWINV2:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 8
  DECODER:
    DEPTH: [3, 2, 1]
    GVI_NUMS: [8, 16, 24]
    FEATURES: [64, 128, 256]
PRINT_FREQ: 1
SAVE_FREQ: 20